[package]
name = "twentytwentytwenty"
version = "0.1.0"
authors = ["Mario Finelli <mario@finel.li>"]
edition = "2018"

[dependencies.notify-rust]
version = "4"
default-features = false
features = ["z"]
